---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# gaborioRtools

<!-- badges: start -->
<!-- badges: end -->

This is my personal package with a bunch of useful functions for data wrangling and analysis

## Installation

You can install the development version of gaborioRtools from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("gaborio/gaborioRtools")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(gaborioRtools)
## basic recode_100 function
# TODO: include data to package so example works
# cols_values <- list(
#   EMO_11 = c("5", "6. Positiva"),
#   PAF_11 = c("5", "6. Honestos"),
#   PAF_14 = c("5", "6. Solidarios"),
#   PAF_03 = c("4", "5. De acuerdo"),
#   PAF_04 = c("4", "5. De acuerdo"),
#   PAF_08 = c("Smiling", "Very happy")
#   )
# for (col in names(cols_values)) {
#   pol_data <- recode_100(pol_data, col, cols_values[[col]])
#   }
```
